---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hoi-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hoi-ui
  template:
    metadata:
      labels:
        app: hoi-ui
    spec:
      containers:
      - name: hoi-ui
        image: bhimanivasu/hoi-ui:latest
        ports:
        - containerPort: 3000   # Use port 3000

---
apiVersion: v1
kind: Service
metadata:
  name: hoi-ui-service
spec:
  selector:
    app: hoi-ui
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 3000
  type: LoadBalancer